apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec:
      containers:
      - name: ai-container
        image: reduced
        resources:
          limits:
            cpu: 5000m
            memory: 1000Mi
        volumeMounts:
        - name: local-storage
          mountPath: /app/models
      volumes:
      - name: local-storage
        hostPath:
          path: /c/code/S3P/models/HF-Phi
          type: Directory