apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec:
      containers:
      - name: ai-container
        image: europe-west3-docker.pkg.dev/optimal-carving-438111-h3/gcp-hf-gpu/gcp-hf-gpu:latest
        resources:
          limits:
            cpu: 100m
            memory: 8192Mi
        volumeMounts:
        - name: local-storage
          mountPath: /app/models
      volumes:
      - name: local-storage
        hostPath:
          path: /path/to/local/models
          type: Directory