apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-xla-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytorch-xla-app
  template:
    metadata:
      labels:
        app: pytorch-xla-app
    spec:
      containers:
      - name: pytorch-xla-app
        image: europe-west3-docker.pkg.dev/optimal-carving-438111-h3/s3p-gcp-k8s/3-gcp-tpu:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "4"           # Adjust CPU limit
            memory: "16Gi"     # Adjust memory limit
          requests:
            cpu: "2"           # Adjust CPU request
            memory: "8Gi"      # Adjust memory request
        volumeMounts:
        - name: fuse-mount
          mountPath: /app/models
      volumes:
      - name: fuse-mount
        emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: pytorch-xla-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: pytorch-xla-app