apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenroom-sentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greenroom-sentiment
  template:
    metadata:
      labels:
        app: greenroom-sentiment
    spec:
      containers:
      - name: greenroom-sentiment
        image: europe-west3-docker.pkg.dev/optimal-carving-438111-h3/s3p-gcp-k8s/greenroom-sentiment:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: greenroom-sentiment
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    app: greenroom-sentiment

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: greenroom-sentiment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: greenroom-sentiment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80