apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenroom-sentiment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greenroom-sentiment
  template:
    metadata:
      labels:
        app: greenroom-sentiment
    spec:
      containers:
      - name: greenroom-sentiment
        image: gcr.io/optimal-carving-438111-h3/greenroom-sentiment:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: greenroom-sentiment
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5001
  selector:
    app: greenroom-sentiment