apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
        cloud.google.com/gke-accelerator-count: "1"
      containers:
      - name: ai-container
        image: europe-west3-docker.pkg.dev/optimal-carving-438111-h3/gcp-hf-gpu/gcp-hf-gpu:latest
        resources:
          limits:
            cpu: 100m
            memory: 8192Mi
            nvidia.com/gpu: 1
        volumeMounts:
        - name: gcs-bucket
          mountPath: /app/models
      volumes:
      - name: gcs-bucket
        csi:
          driver: gcp.csi.storage.gcs
          volumeAttributes:
            bucketName: s3-model-data-oc
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: In
                values:
                - nvidia-tesla-t4